"""Extract Medium and Mini cut contours from the LightBurn files into JSON.

Large already lives in source/source-data.js and is NOT touched by this script -
that file is the audited original. This writes source/size-contours.json holding
the two new sizes in the same shape, so build.py can load any size uniformly.

Two things the naive reader gets wrong, both of which matter:

  * XForm is a CHILD element, not an attribute, and shapes reference a shared
    <VertList> by VertID - later shapes carry only an XForm. Miss that and most
    shapes parse as empty.
  * Medium and Mini outlines are 8 vertices with 4 CUBIC corners, unlike Large's
    409 flat vertices. Keeping vertices only turns the swept corners into straight
    chamfers, an error of up to 5.99 mm on Medium. The Beziers must be flattened.

LightBurn Y increases upward; SVG Y increases downward, so Y is flipped here and
the result is normalised to a (0,0) top-left origin.

    python extract-size-contours.py
"""

import json
import os
import re
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
CUTS = r"F:\sean\max\cutting files street signs"

SOURCES = {
    "medium": {"file": "MIDDLE size  halfbed JUN26.lbrn2", "blank": (450.0, 120.0)},
    "mini":   {"file": "MINI TRADITIONAL ROAD SIGN SHAPE - Copy.lbrn2", "blank": (289.723, 85.0)},
}

VERT_RE = re.compile(
    r"V(-?[\d.eE+-]+)\s+(-?[\d.eE+-]+)"
    r"(?:c0x(-?[\d.eE+-]+))?(?:c0y(-?[\d.eE+-]+))?"
    r"(?:c1x(-?[\d.eE+-]+))?(?:c1y(-?[\d.eE+-]+))?"
)
PRIM_RE = re.compile(r"([LB])\s*(\d+)\s+(\d+)")
STEPS = 48  # ~0.02mm chord error on a 13mm corner


def fnum(v):
    return float(v) if v not in (None, "") else None


def cubic(p0, c0, c1, p1):
    out = []
    for i in range(1, STEPS + 1):
        t = i / STEPS
        m = 1 - t
        out.append((
            m**3*p0[0] + 3*m*m*t*c0[0] + 3*m*t*t*c1[0] + t**3*p1[0],
            m**3*p0[1] + 3*m*m*t*c0[1] + 3*m*t*t*c1[1] + t**3*p1[1],
        ))
    return out


def first_outline_and_holes(path):
    root = ET.parse(path).getroot()
    vcache, pcache = {}, {}
    outline = None
    holes_world = []
    outline_xf = None

    for sh in root.iter("Shape"):
        xf_el = sh.find("XForm")
        xf = [float(v) for v in xf_el.text.split()] if xf_el is not None else [1, 0, 0, 1, 0, 0]
        a, b, c, d, e, f = xf

        if sh.get("Type") == "Ellipse":
            holes_world.append((e, f, float(sh.get("Rx")) * a))
            continue

        vid, pid = sh.get("VertID"), sh.get("PrimID")
        vl, pl = sh.find("VertList"), sh.find("PrimList")
        if vl is not None:
            vcache[vid] = [
                {"p": (float(m.group(1)), float(m.group(2))),
                 "c0": (fnum(m.group(3)), fnum(m.group(4))),
                 "c1": (fnum(m.group(5)), fnum(m.group(6)))}
                for m in VERT_RE.finditer(vl.text or "")
            ]
        if pl is not None:
            pcache[pid] = PRIM_RE.findall(pl.text or "")
        verts, prims = vcache.get(vid), pcache.get(pid)
        if not verts or outline is not None:
            continue

        pts = []
        for kind, ia, ib in prims:
            va, vb = verts[int(ia)], verts[int(ib)]
            pts.append(va["p"])
            if kind == "B" and va["c0"][0] is not None and vb["c1"][0] is not None:
                pts.extend(cubic(va["p"], va["c0"], vb["c1"], vb["p"]))
        outline = [(a*x + c*y + e, b*x + d*y + f) for x, y in pts]
        outline_xf = (e, f)
        nverts, nbez = len(verts), sum(1 for k, _, _ in prims if k == "B")

    return outline, holes_world, outline_xf, nverts, nbez


def main():
    result = {"_note": "Generated by source/extract-size-contours.py. Large stays in source-data.js.",
              "sizes": {}}

    for name, cfg in SOURCES.items():
        path = os.path.join(CUTS, cfg["file"])
        if not os.path.exists(path):
            raise SystemExit(f"Cut file not found (is the USB drive attached?): {path}")

        outline, holes, origin, nverts, nbez = first_outline_and_holes(path)
        if not outline:
            raise SystemExit(f"No outline found in {cfg['file']}")

        xs = [p[0] for p in outline]
        ys = [p[1] for p in outline]
        w = max(xs) - min(xs)
        h = max(ys) - min(ys)
        bw, bh = cfg["blank"]
        if abs(w - bw) > 0.05 or abs(h - bh) > 0.05:
            raise SystemExit(f"{name}: measured {w:.3f}x{h:.3f} but expected {bw}x{bh} - refusing to guess.")

        # normalise to 0,0 top-left and flip Y (LightBurn up -> SVG down)
        x0, y1 = min(xs), max(ys)
        norm = [{"x": round(px - x0, 4), "y": round(y1 - py, 4)} for px, py in outline]

        # holes belonging to this blank, in the same normalised space
        near = []
        for hx, hy, r in holes:
            nx, ny = hx - x0, y1 - hy
            if -1 <= nx <= w + 1 and -1 <= ny <= h + 1:
                near.append({"x": round(nx, 4), "y": round(ny, 4), "radius": round(r, 4)})

        result["sizes"][name] = {
            "blankWidthMm": round(w, 3),
            "blankHeightMm": round(h, 3),
            "sourceFile": cfg["file"],
            "sourceVertices": nverts,
            "cubicCorners": nbez,
            "contour": {"points": norm},
            "mountingHoles": near,
        }
        print(f"{name:7s} {w:8.3f} x {h:7.3f} mm | {nverts} verts + {nbez} cubics -> {len(norm)} pts | holes {len(near)}")

    out = os.path.join(HERE, "size-contours.json")
    with open(out, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=1)
    print(f"wrote {out} ({os.path.getsize(out):,} bytes)")


if __name__ == "__main__":
    main()
