#!/usr/bin/env python3
"""Monitor @daisymaison on TikTok from outside. No login, no app, no audit.

    python tiktok_public.py profile
    python tiktok_public.py profile --save        # snapshot; deltas vs the last one
    python tiktok_public.py profile --user treatbox

What this can and cannot see
----------------------------
TikTok renders a public profile from a JSON blob embedded in the page
(`__UNIVERSAL_DATA_FOR_REHYDRATION__`). That blob is fetchable with one plain
request and carries account-level stats: followers, following, video count, and
**heartCount — the cumulative total of every like the account has ever
received.**

It does NOT carry the video grid. The tiles load separately from
`api/post/item_list`, which answers 200 with an empty body unless the request
is signed, and the signature is generated by TikTok's own obfuscated JS. A
headless browser would sidestep that, but Chromium cannot reach tiktok.com
through this container's proxy (ERR_CONNECTION_RESET) while plain HTTP can. So:
**no per-video views, likes or comments.** Do not claim otherwise.

Why account level is still worth having
---------------------------------------
`heartCount` is cumulative, so the DIFFERENCE between two daily snapshots is
the number of likes the account earned in between. Take one snapshot a day and
you get a daily engagement series without ever seeing a single video's stats —
which is exactly the number that tells us whether a day's posting worked.

Same for `videoCount`: its delta says how many posts actually went live, which
independently verifies our own publish log rather than trusting it.

This is a proxy, not a measurement. It cannot attribute a spike to a specific
post on a day we published more than once, and it cannot see views at all. Say
so whenever you quote it.
"""
import argparse
import datetime
import glob
import json
import os
import re
import sys

import requests

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
BLOB = re.compile(
    r'id="__UNIVERSAL_DATA_FOR_REHYDRATION__"[^>]*>(.*?)</script>', re.S)

HERE = os.path.dirname(os.path.abspath(__file__))
SNAPSHOT_DIR = os.path.join(HERE, "tiktok-snapshots")


def fetch(username):
    r = requests.get("https://www.tiktok.com/@%s" % username,
                     headers={"User-Agent": UA,
                              "Accept-Language": "en-GB,en;q=0.9"},
                     timeout=30)
    if r.status_code != 200:
        sys.exit("TikTok returned HTTP %d for @%s." % (r.status_code, username))
    m = BLOB.search(r.text)
    if not m:
        sys.exit("Could not find the rehydration blob - TikTok changed the "
                 "page shape, or served a challenge instead of the profile.")
    scope = json.loads(m.group(1)).get("__DEFAULT_SCOPE__", {})
    info = (scope.get("webapp.user-detail") or {}).get("userInfo") or {}
    if not info:
        sys.exit("Profile blob had no userInfo. Account may be private, "
                 "renamed or removed.")
    return info


def previous_snapshot(username):
    """Most recent earlier snapshot, so we can report deltas."""
    paths = sorted(glob.glob(os.path.join(SNAPSHOT_DIR, "%s-*.json" % username)))
    if not paths:
        return None
    try:
        return json.load(open(paths[-1]))
    except (ValueError, OSError):
        return None


def cmd_profile(a):
    info = fetch(a.user)
    stats = info.get("stats") or info.get("statsV2") or {}
    user = info.get("user") or {}

    def num(k):
        v = stats.get(k)
        return int(v) if v is not None and str(v).isdigit() else v

    snap = {
        "pulled_utc": datetime.datetime.utcnow().isoformat(),
        "username": a.user,
        "nickname": user.get("nickname"),
        "followers": num("followerCount"),
        "following": num("followingCount"),
        "videos": num("videoCount"),
        # Cumulative likes across every video, ever. The delta is the point.
        "hearts_total": num("heartCount"),
    }

    prev = previous_snapshot(a.user)

    if a.save:
        os.makedirs(SNAPSHOT_DIR, exist_ok=True)
        # Intra-day pulls used to overwrite each other, so a second run
        # silently destroyed the morning reading it was being compared
        # against. Found by testing on 28 Jul. Keep every pull; the
        # first of a day keeps the plain date so the series stays
        # readable, later ones get a time suffix.
        base = os.path.join(SNAPSHOT_DIR, "%s-%s" % (
            a.user, datetime.date.today().isoformat()))
        p = base + ".json"
        if os.path.exists(p):
            p = "%s-%s.json" % (base, datetime.datetime.utcnow().strftime("%H%M"))
        json.dump(snap, open(p, "w"), indent=2)
        print("saved %s" % p, file=sys.stderr)

    if a.json:
        print(json.dumps({"now": snap, "previous": prev}, indent=2))
        return

    print("@%s (%s) - %s followers, %s videos, %s total likes" % (
        snap["username"], snap["nickname"], snap["followers"],
        snap["videos"], snap["hearts_total"]))

    if snap["followers"] and snap["hearts_total"] and snap["videos"]:
        print("lifetime average %.1f likes per video" % (
            snap["hearts_total"] / snap["videos"]))

    if prev and prev.get("hearts_total") is not None:
        dh = snap["hearts_total"] - prev["hearts_total"]
        dv = (snap["videos"] or 0) - (prev.get("videos") or 0)
        df = (snap["followers"] or 0) - (prev.get("followers") or 0)
        print("\nsince %s: %+d likes, %+d videos, %+d followers"
              % (prev["pulled_utc"][:10], dh, dv, df))
        if dv > 1:
            print("  %d posts went live in that window, so the like gain "
                  "cannot be attributed to any single one." % dv)
    else:
        print("\nNo earlier snapshot to compare against. Run with --save daily; "
              "the delta between snapshots is the whole point of this tool.")

    print("\nPer-video views, likes and comments are NOT available externally - "
          "TikTok signs that endpoint. Never quote a per-post TikTok figure "
          "from this tool.")


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("profile", help="account stats + delta vs last snapshot")
    p.add_argument("--user", default="daisymaison")
    p.add_argument("--json", action="store_true")
    p.add_argument("--save", action="store_true")
    p.set_defaults(fn=cmd_profile)
    a = ap.parse_args()
    a.fn(a)


if __name__ == "__main__":
    main()
